<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ItemSalesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('item_sales')->delete();
        
        \DB::table('item_sales')->insert(array (
            0 => 
            array (
                'id' => 1,
                'category_id' => 1,
                'image' => 'item-sales/October2025/OfrW0eQ83FMSXMHZJsFIday08am.avif',
                'name' => 'Ala Broaster Economico',
                'price' => '14.00',
                'observation' => NULL,
                'typeSale' => 'Venta Sin Stock',
                'status' => 1,
                'created_at' => '2025-10-07 16:14:21',
                'updated_at' => '2025-10-11 12:47:52',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'category_id' => 1,
                'image' => 'item-sales/October2025/trP6QVftX3EJL8ZHaxNYday08am.avif',
                'name' => 'Pechuga Broaster Economico',
                'price' => '14.00',
                'observation' => NULL,
                'typeSale' => 'Venta Sin Stock',
                'status' => 1,
                'created_at' => '2025-10-07 16:27:56',
                'updated_at' => '2025-10-11 12:47:31',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'category_id' => 1,
                'image' => 'item-sales/October2025/tZbMCJ72lgVJ42T3NZ1Eday08am.avif',
                'name' => 'Pierna Broaster Econ.',
                'price' => '14.00',
                'observation' => NULL,
                'typeSale' => 'Venta Sin Stock',
                'status' => 1,
                'created_at' => '2025-10-07 16:29:20',
                'updated_at' => '2025-10-11 12:37:36',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'category_id' => 1,
                'image' => 'item-sales/October2025/sOX1T6VcWzUc4g7kf8kfday08am.avif',
                'name' => 'Entrepierna Broaster Econ.',
                'price' => '14.00',
                'observation' => NULL,
                'typeSale' => 'Venta Sin Stock',
                'status' => 1,
                'created_at' => '2025-10-07 16:30:54',
                'updated_at' => '2025-10-11 12:47:12',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'category_id' => 1,
                'image' => 'item-sales/October2025/Dfln0ov1xsUVI4YeS02Rday08am.avif',
                'name' => 'Pierna Spiedo Econ.',
                'price' => '14.00',
                'observation' => NULL,
                'typeSale' => 'Venta Sin Stock',
                'status' => 1,
                'created_at' => '2025-10-07 16:32:18',
                'updated_at' => '2025-10-11 12:44:02',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'category_id' => 1,
                'image' => 'item-sales/October2025/G9BJEWxa4vPcUfR1VA5zday08am.avif',
                'name' => 'Pechuga Spiedo Econ.',
                'price' => '14.00',
                'observation' => NULL,
                'typeSale' => 'Venta Sin Stock',
                'status' => 1,
                'created_at' => '2025-10-07 16:32:43',
                'updated_at' => '2025-10-11 12:43:47',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'category_id' => 1,
                'image' => 'item-sales/October2025/kvs2bS9g7j6o9bHrrTswday08am.avif',
                'name' => 'Ala Spiedo Econ.',
                'price' => '14.00',
                'observation' => NULL,
                'typeSale' => 'Venta Sin Stock',
                'status' => 1,
                'created_at' => '2025-10-07 16:33:29',
                'updated_at' => '2025-10-11 12:43:13',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'category_id' => 1,
                'image' => 'item-sales/October2025/ciKTfqAWhRlkQi1IeeB6day08am.avif',
                'name' => 'Entrepierna Spiedo Econ.',
                'price' => '14.00',
                'observation' => NULL,
                'typeSale' => 'Venta Sin Stock',
                'status' => 1,
                'created_at' => '2025-10-07 16:35:04',
                'updated_at' => '2025-10-11 12:37:12',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'category_id' => 2,
                'image' => 'item-sales/October2025/HCnrCaVrn6YfVF9VKizTday08pm.avif',
                'name' => 'Cola-Cola 3 Ltro',
                'price' => '20.00',
                'observation' => NULL,
                'typeSale' => 'Venta Sin Stock',
                'status' => 1,
                'created_at' => '2025-10-08 08:50:09',
                'updated_at' => '2025-10-11 12:36:52',
                'registerUser_id' => 2,
                'registerRole' => 'administrador',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'category_id' => 2,
                'image' => 'item-sales/October2025/TBTFU0Tp2WPawtb9YzYEday08pm.avif',
                'name' => 'Coca-Cola 2 Ltro',
                'price' => '15.00',
                'observation' => NULL,
                'typeSale' => 'Venta Sin Stock',
                'status' => 1,
                'created_at' => '2025-10-08 08:51:14',
                'updated_at' => '2025-10-08 08:51:24',
                'registerUser_id' => 2,
                'registerRole' => 'administrador',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'category_id' => 2,
                'image' => 'item-sales/October2025/6kNpQN0LtjoeJ4uF8W8Aday08pm.avif',
                'name' => 'Coca-Cola Personal',
                'price' => '3.00',
                'observation' => NULL,
                'typeSale' => 'Venta Sin Stock',
                'status' => 1,
                'created_at' => '2025-10-08 08:53:38',
                'updated_at' => '2025-10-08 08:53:38',
                'registerUser_id' => 2,
                'registerRole' => 'administrador',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'category_id' => 2,
                'image' => 'item-sales/October2025/AndehlgGPu1TFeofmywaday08pm.avif',
                'name' => 'Coca-cola 1 Ltro',
                'price' => '7.00',
                'observation' => NULL,
                'typeSale' => 'Venta Sin Stock',
                'status' => 0,
                'created_at' => '2025-10-08 08:55:13',
                'updated_at' => '2025-10-11 12:42:26',
                'registerUser_id' => 2,
                'registerRole' => 'administrador',
                'deleted_at' => '2025-10-11 12:42:26',
                'deleteUser_id' => 2,
                'deleteRole' => 'administrador',
                'deleteObservation' => 'fea',
            ),
            12 => 
            array (
                'id' => 13,
                'category_id' => 1,
                'image' => NULL,
                'name' => 'Lomo',
                'price' => '15.00',
                'observation' => NULL,
                'typeSale' => 'Venta Sin Stock',
                'status' => 1,
                'created_at' => '2025-10-11 11:45:32',
                'updated_at' => '2025-10-11 11:45:32',
                'registerUser_id' => 2,
                'registerRole' => 'administrador',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'category_id' => 1,
                'image' => NULL,
                'name' => 'Cuarto Pierna Broaster',
                'price' => '28.00',
                'observation' => NULL,
                'typeSale' => 'Venta Sin Stock',
                'status' => 1,
                'created_at' => '2025-10-11 12:38:38',
                'updated_at' => '2025-10-11 12:40:01',
                'registerUser_id' => 2,
                'registerRole' => 'administrador',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'category_id' => 1,
                'image' => NULL,
                'name' => 'Cuarto Pecho Broaster',
                'price' => '28.00',
                'observation' => NULL,
                'typeSale' => 'Venta Sin Stock',
                'status' => 1,
                'created_at' => '2025-10-11 12:39:26',
                'updated_at' => '2025-10-11 12:39:41',
                'registerUser_id' => 2,
                'registerRole' => 'administrador',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'category_id' => 2,
                'image' => NULL,
                'name' => 'triny-popular',
                'price' => '6.00',
                'observation' => NULL,
                'typeSale' => 'Venta Sin Stock',
                'status' => 1,
                'created_at' => '2025-10-11 12:53:07',
                'updated_at' => '2025-10-11 12:53:07',
                'registerUser_id' => 2,
                'registerRole' => 'administrador',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'category_id' => 1,
                'image' => NULL,
                'name' => 'Una,presa',
                'price' => '10.00',
                'observation' => NULL,
                'typeSale' => 'Venta Sin Stock',
                'status' => 1,
                'created_at' => '2025-10-11 15:26:50',
                'updated_at' => '2025-10-11 17:46:16',
                'registerUser_id' => 2,
                'registerRole' => 'administrador',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
        ));
        
        
    }
}